# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!

# ref: <https://github.com/astral-sh/ruff/pull/22021>
# ref: <https://github.com/microsoft/pyright/blob/main/docs/builtins.md>

from typing import overload, type_check_only

@type_check_only
class _IceCreamDebugger:
    @overload
    def __call__(self, **kwargs) -> None: ...
    @overload
    def __call__[T](self, arg: T, **kwargs) -> T: ...
    @overload
    def __call__[T1, T2, *Ts](
        self, arg1: T1, arg2: T2, *args: *Ts, **kwargs
    ) -> tuple[T1, T2, *Ts]: ...

ic: _IceCreamDebugger

__all__ = ["ic"]
