#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
set -o errexit
set -o nounset
set -o pipefail

function is-true() {
  case "${1,,}" in
    1 | on | true | y | yes) return 0 ;;
    0 | off | false | n | no | "") return 1 ;;
    *)
      echo "Invalid boolean: $1." >&2
      exit 1
      ;;
  esac
}

# ref: <https://github.com/scientific-python/lazy-loader#early-failure>
export EAGER_IMPORT=1

if is-true "${CI-}"; then
  pytest --junit-xml="junit.xml" --cov --cov-branch --numprocesses="auto" "$@"
else
  pytest --numprocesses="auto" "$@"
fi
