#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
# [MISE] depends_post=["lint:toml"]
set -o errexit
set -o nounset
set -o pipefail

function has() {
  type "$@" &> /dev/null
}

function lock() {
  local -r root="${MISE_PROJECT_ROOT:-"$PWD"}"
  local -r name="$(basename -- "${root}")"
  mkdir --parents --verbose '/tmp/mise-flock'
  flock --nonblock --verbose "/tmp/mise-flock/$name.lock" "$@"
}

if [[ -f 'pixi.lock' ]]; then
  if has pypi-lock-wrapper.sh; then
    pixi=(pypi-lock-wrapper.sh pixi)
  else
    pixi=(pixi)
  fi
  lock "${pixi[@]}" upgrade "$@"
fi

if [[ -f 'uv.lock' ]]; then
  if has uv-sync.py; then
    uv_sync=(uv-sync.py)
  else
    uv_sync=(uv sync)
  fi
  lock "${uv_sync[@]}" --upgrade "$@"
fi
