#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
# [MISE] depends_post=["lint"]
set -o errexit
set -o nounset
set -o pipefail

function has() {
  type "$@" &> /dev/null
}

if [[ -f 'pixi.lock' ]]; then
  pixi='pixi'
  if has pixi-wrapper.sh; then pixi='pixi-wrapper.sh'; fi
  "$pixi" upgrade "$@"
fi

if [[ -f 'uv.lock' ]]; then
  uv='uv'
  if has uv-wrapper.sh; then uv='uv-wrapper.sh'; fi
  "$uv" sync --upgrade "$@"
fi
