#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
set -o errexit
set -o nounset
set -o pipefail

function has() {
  type "$@" &> /dev/null
}

function toml-sort-wrapper() {
  local files=()
  for file in "$@"; do
    if [[ -f $file ]]; then
      files+=("$file")
    fi
  done
  if has toml-sort; then
    toml-sort --in-place --all "${files[@]}"
    sed --expression='s/# :schema /#:schema /g' --in-place "${files[@]}"
  fi
}

toml-sort-wrapper 'pyproject.toml'

if has tombi; then
  tombi format
  tombi lint
fi
