name: Update LICENSE Year

on:
  schedule:
    - cron: 0 3 1 1 * # 3:00 AM on January 1st

permissions:
  contents: write

jobs:
  license:
    name: Update LICENSE Year
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update LICENSE Year
        uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ github.token }}
